package com.sanches.wifianalyzer;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.*;import android.net.wifi.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 private WifiManager wifi; private Handler handler=new Handler(Looper.getMainLooper()); private TextView ssid,signal,band,channel,link,status,scanInfo; private LinearLayout networks; private Runnable monitor; private boolean scanning=false;
 private final BroadcastReceiver scanReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){ if(WifiManager.SCAN_RESULTS_AVAILABLE_ACTION.equals(i.getAction())){scanning=false; renderNetworks(); updateConnection();}}};
 @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(11,16,32));getWindow().setNavigationBarColor(Color.rgb(11,16,32));setContentView(com.sanches.wifianalyzer.R.layout.activity_main); bind(); requestPerms(); registerReceiver(scanReceiver,new IntentFilter(WifiManager.SCAN_RESULTS_AVAILABLE_ACTION)); startEcoMonitor();}
 private void bind(){ssid=findViewById(R.id.ssid);signal=findViewById(R.id.signalBig);band=findViewById(R.id.band);channel=findViewById(R.id.channel);link=findViewById(R.id.link);status=findViewById(R.id.status);scanInfo=findViewById(R.id.scanInfo);networks=findViewById(R.id.networks); findViewById(R.id.scanButton).setOnClickListener(v->scan()); findViewById(R.id.diagnoseButton).setOnClickListener(v->diagnose());}
 private void requestPerms(){ArrayList<String> p=new ArrayList<>();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.NEARBY_WIFI_DEVICES)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.NEARBY_WIFI_DEVICES);if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.ACCESS_FINE_LOCATION);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),41);else updateConnection();}
 private void startEcoMonitor(){monitor=()->{updateConnection();handler.postDelayed(monitor,15000);};handler.postDelayed(monitor,2500);}
 private void updateConnection(){try{WifiInfo w=wifi().getConnectionInfo();String s=w.getSSID();if(s==null||s.equals("<unknown ssid>")){ssid.setText("Nenhuma rede identificada");status.setText("● SEM WI-FI");signal.setText("-- dBm");return;}ssid.setText(s.replace("\"",""));int r=w.getRssi();signal.setText(r+" dBm");status.setText("● CONECTADO • "+quality(r));int f=w.getFrequency();band.setText("BANDA\n"+(f>=5925?"6 GHz":f>=4900?"5 GHz":"2,4 GHz"));channel.setText("CANAL\n"+channelFromFreq(f));link.setText("LINK\n"+(w.getLinkSpeed()>=0?w.getLinkSpeed()+" Mbps":"--"));}catch(Exception e){status.setText("● DADOS RESTRITOS PELO ANDROID");}}
 private WifiManager wifi(){if(wifi==null)wifi=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);return wifi;}
 private String quality(int r){if(r>=-50)return"SINAL EXCELENTE";if(r>=-60)return"SINAL FORTE";if(r>=-67)return"SINAL BOM";if(r>=-75)return"SINAL FRACO";return"SINAL MUITO FRACO";}
 private int channelFromFreq(int f){if(f>=2412&&f<=2484)return (f-2407)/5;if(f>=5000)return (f-5000)/5;return 0;}
 private void scan(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPerms();return;} if(scanning)return;scanning=true;scanInfo.setText("Escaneando…");status.setText("● ESCANEANDO");boolean ok=wifi().startScan();if(!ok){scanning=false;scanInfo.setText("O Android limitou a varredura. Tente novamente em alguns segundos.");renderNetworks();}}
 private void renderNetworks(){networks.removeAllViews();try{List<ScanResult> list=new ArrayList<>(wifi().getScanResults());Collections.sort(list,(a,b)->Integer.compare(b.level,a.level));HashSet<String> seen=new HashSet<>();int shown=0;for(ScanResult n:list){String key=n.SSID+"|"+n.frequency;if(n.SSID==null||n.SSID.isEmpty()||seen.contains(key))continue;seen.add(key);addNetwork(n);if(++shown>=30)break;}scanInfo.setText(shown+" redes encontradas • atualizado agora");}catch(Exception e){scanInfo.setText("Não foi possível ler as redes disponíveis.");}}
 private void addNetwork(ScanResult n){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(16,13,16,13);card.setBackgroundResource(R.drawable.bg_card);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT);cp.setMargins(0,0,0,8);card.setLayoutParams(cp);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView name=t(n.SSID,16,Color.WHITE);name.setTypeface(null,1);row.addView(name,new LinearLayout.LayoutParams(0,42,1));TextView sig=t(n.level+" dBm",14,signalColor(n.level));row.addView(sig,new LinearLayout.LayoutParams(90,42));card.addView(row);TextView info=t((n.frequency>=5925?"6 GHz":n.frequency>=4900?"5 GHz":"2,4 GHz")+"  •  Canal "+channelFromFreq(n.frequency)+"  •  "+security(n),12,Color.rgb(130,144,174));card.addView(info);networks.addView(card);}
 private String security(ScanResult n){String c=n.capabilities==null?"Aberta":n.capabilities; if(c.contains("WPA3"))return"WPA3";if(c.contains("WPA2"))return"WPA2";if(c.contains("WPA"))return"WPA";return"Aberta";}
 private int signalColor(int r){return r>=-60?Color.rgb(99,214,162):r>=-75?Color.rgb(255,193,7):Color.rgb(255,100,100);}
 private TextView t(String x,int size,int color){TextView v=new TextView(this);v.setText(x);v.setTextSize(size);v.setTextColor(color);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private void diagnose(){try{WifiInfo w=wifi().getConnectionInfo();int r=w.getRssi();String msg="SINAL: "+quality(r)+" ("+r+" dBm)\n\nBANDA: "+band.getText().toString().replace("BANDA\n","")+"\nCANAL: "+channel.getText().toString().replace("CANAL\n","")+"\nLINK: "+link.getText().toString().replace("LINK\n","")+"\n\nDica: mantenha o roteador livre de obstáculos e, se houver muitas redes no mesmo canal, considere trocar o canal no roteador.";new AlertDialog.Builder(this).setTitle("Diagnóstico da conexão").setMessage(msg).setPositiveButton("OK",null).show();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Diagnóstico").setMessage("Conecte-se a uma rede Wi-Fi para analisar.").setPositiveButton("OK",null).show();}}
 @Override protected void onDestroy(){super.onDestroy();handler.removeCallbacksAndMessages(null);try{unregisterReceiver(scanReceiver);}catch(Exception ignored){}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);updateConnection();}
}
