package br.com.sanches.controleartes;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout root,list;TextView total,receber,pago,atrasado;ArrayList<JSONObject>items=new ArrayList<>();android.content.SharedPreferences sp;Uri pendingImage;int green=Color.rgb(37,211,102),bg=Color.rgb(11,15,20),card=Color.rgb(22,29,38);
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("dados",0);load();build();}
 TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(z);t.setPadding(18,10,18,10);return t;}Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);root.setBackgroundColor(bg);TextView h=tv("💰 CONTROLE DE ARTES VIP",22);h.setTextColor(green);root.addView(h);total=tv("",17);receber=tv("",17);pago=tv("",17);atrasado=tv("",17);root.addView(total);root.addView(receber);root.addView(pago);root.addView(atrasado);Button add=btn("＋ NOVA ARTE");add.setOnClickListener(v->form(null));root.addView(add);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);refresh();}
 void form(JSONObject old){Dialog d=new Dialog(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(24,20,24,20);l.setBackgroundColor(card);EditText c=new EditText(this),v=new EditText(this),x=new EditText(this);c.setHint("Empresa / cliente");v.setHint("Valor (ex.: 10,00)");x.setHint("Descrição da arte");v.setInputType(2|8192);l.addView(tv(old==null?"Nova arte":"Editar arte",20));l.addView(c);l.addView(v);l.addView(x);Button f=btn("📸 Selecionar foto"),s=btn("SALVAR");l.addView(f);l.addView(s);if(old!=null){c.setText(old.optString("cliente"));v.setText(old.optString("valor"));x.setText(old.optString("desc"));}f.setOnClickListener(q->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,101);});s.setOnClickListener(q->{try{JSONObject o=old==null?new JSONObject():old;o.put("cliente",c.getText().toString());o.put("valor",v.getText().toString());o.put("desc",x.getText().toString());if(old==null)o.put("status","A receber");if(pendingImage!=null){o.put("foto",pendingImage.toString());pendingImage=null;}if(old==null)items.add(o);save();refresh();d.dismiss();}catch(Exception e){}});d.setContentView(l);d.show();}
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==101&&c==RESULT_OK&&data!=null)pendingImage=data.getData();}
 void refresh(){list.removeAllViews();double rec=0,pag=0,atr=0;for(JSONObject o:items){double n=num(o.optString("valor"));String st=o.optString("status");if(st.equals("A receber")||st.equals("Arte entregue"))rec+=n;if(st.equals("Pago"))pag+=n;if(st.contains("atras"))atr+=n;card(o);}total.setText("💵 Total: R$ "+money(rec+pag));receber.setText("🟡 A receber: R$ "+money(rec));pago.setText("🟢 Pago: R$ "+money(pag));atrasado.setText("🔴 Atrasado: R$ "+money(atr));}
 void card(JSONObject o){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(12,12,12,12);c.setBackgroundColor(card);c.addView(tv(o.optString("cliente")+" • R$ "+o.optString("valor"),18));c.addView(tv(o.optString("desc")+"\nStatus: "+o.optString("status"),14));LinearLayout b=new LinearLayout(this);Button st=btn("STATUS"),z=btn("💬 COBRAR"),e=btn("EDITAR");b.addView(st,new LinearLayout.LayoutParams(0,-2,1));b.addView(z,new LinearLayout.LayoutParams(0,-2,1));b.addView(e,new LinearLayout.LayoutParams(0,-2,1));c.addView(b);st.setOnClickListener(v->status(o));z.setOnClickListener(v->whats(o));e.setOnClickListener(v->form(o));list.addView(c);Space spc=new Space(this);list.addView(spc,new LinearLayout.LayoutParams(1,8));}
 void status(JSONObject o){String[] a={"A receber","Arte entregue","Pago","Arte atrasada","Pagamento atrasado"};new AlertDialog.Builder(this).setTitle("Status").setItems(a,(d,w)->{try{o.put("status",a[w]);save();refresh();}catch(Exception e){}}).show();}
 void whats(JSONObject o){String msg="Olá, "+o.optString("cliente")+"! 👋\n\nPassando para lembrar do pagamento da arte: "+(o.optString("desc").isEmpty()?"arte":o.optString("desc"))+".\nValor: R$ "+o.optString("valor")+"\n\nQuando puder, me envie o pagamento. Obrigado!";Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,msg);try{startActivity(Intent.createChooser(i,"Enviar cobrança pelo WhatsApp"));}catch(Exception e){}}
 double num(String s){try{return Double.parseDouble(s.replace(".","").replace(",","."));}catch(Exception e){return 0;}}String money(double x){return String.format(Locale.US,"%.2f",x).replace(".",",");}
 void save(){JSONArray a=new JSONArray();for(JSONObject o:items)a.put(o);sp.edit().putString("items",a.toString()).apply();}void load(){try{JSONArray a=new JSONArray(sp.getString("items","[]"));for(int i=0;i<a.length();i++)items.add(a.getJSONObject(i));}catch(Exception e){}}
}
